# Generated by Django 5.0.6 on 2024-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("image", models.ImageField(upload_to="image")),
                ("title2", models.CharField(max_length=155)),
                ("descriptions", models.TextField()),
                ("video", models.CharField(max_length=155)),
                ("image2", models.ImageField(upload_to="video/")),
            ],
            options={
                "verbose_name_plural": "О нас",
            },
        ),
    ]
